'use client'
// import type { Metadata } from 'next'
import './globals.css'
import { AppProvider, QueryProvider } from '@/providers/providers'
import { Header } from '@/components/Header/Header'
import { Body, Content, Main } from '@/styles/Styles.style'
import { Poppins } from 'next/font/google'
import { usePathname } from 'next/navigation'

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const pathname = usePathname()
  const isSession = pathname.startsWith('/session') ? 'isSession' : ''

  return (
    <html lang='en' className={poppins.className}>
      <body>
        <QueryProvider>
          <AppProvider>
            <Body>
              <Content>
                <Header />
                <Main className={isSession}>{children}</Main>
              </Content>
            </Body>
          </AppProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
