'use client'
// import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { AppProvider, QueryProvider } from '@/providers/providers'
import { Header } from '@/components/Header/Header'
import { Body, Content, Main } from '@/styles/Styles.style'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <QueryProvider>
          <AppProvider>
            <Body>
              <Content>
                <Header />
                <Main>{children}</Main>
              </Content>
            </Body>
          </AppProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
